#
# $Id: Makefile.in,v 1.7 2002/05/02 12:53:05 mt Exp $
#
# Makefile (Template) for SuSE Proxy Suite -- Top Level
#
# Please do NOT edit this file if its name is just Makefile.
# Instead, edit Makefile.in and run "./configure [options]".
#
# Author(s): Jens-Gero Boehm <jens-gero.boehm@suse.de>
#            Pieter Hollants <pieter.hollants@suse.de>
#            Marius Tomaschewski <mt@suse.de>
#            Volker Wiegand <volker.wiegand@suse.de>
#
# This file is part of the SuSE Proxy Suite
#            See also  http://proxy-suite.suse.de/
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#
# A history log can be found at the end of this file.
#

prefix=		/usr
exec_prefix=	/usr
datadir=	${prefix}/share
docdir?=	$(datadir)/doc/proxy-suite

INSTALL=	/usr/bin/install -c
INSTALL_DATA=	${INSTALL} -m 644

SHELL=		/bin/sh



SUBDIRS=	doc common ftp-proxy

DOCS=		AUTHORS COPYING CREDITS

############################################################

all install:
	@for i in $(SUBDIRS); \
	do \
		echo ""; \
		echo "::::::::::::: make '$@' in ./$$i"; \
		cd $$i && $(MAKE) $@ && cd .. || exit 1; \
	done


install.doc:
	$(INSTALL) -d $(INST_ROOT)$(docdir)
	$(INSTALL_DATA) $(DOCS) $(INST_ROOT)$(docdir)
	@for i in $(SUBDIRS); \
	do \
		echo ""; \
		echo "::::::::::::: make '$@' in ./$$i"; \
		cd $$i && $(MAKE) $@ && cd .. || exit 1; \
	done


############################################################

clean:
	@for i in $(SUBDIRS); \
	do \
		echo ""; \
		echo "::::::::::::: make '$@' in ./$$i"; \
		cd $$i \
			&& $(MAKE) -f Makefile.in $@ \
			&& cd .. || exit 1; \
	done

distclean:
	rm -f config.status config.cache config.log
	rm -f Makefile config.h
	@for i in $(SUBDIRS); \
	do \
		echo ""; \
		echo "::::::::::::: make '$@' in ./$$i"; \
		cd $$i \
			&& $(MAKE) -f Makefile.in $@ \
			&& cd .. || exit 1; \
	done

realclean:
	rm -f config.status config.cache config.log
	rm -f Makefile config.h config.h.in configure
	@for i in $(SUBDIRS); \
	do \
		echo ""; \
		echo "::::::::::::: make '$@' in ./$$i"; \
		cd $$i \
			&& $(MAKE) -f Makefile.in $@ \
			&& cd .. || exit 1; \
	done


############################################################
# $Log: Makefile.in,v $
# Revision 1.7  2002/05/02 12:53:05  mt
# merged with 1.8.2.2
#
# Revision 1.6.2.1  2002/01/27 21:20:38  mt
# fixed Makefiles to use INST_ROOT, added install.doc targets
#
# Revision 1.6  2002/01/14 19:50:54  mt
# added rm -f config.cache in clean target
#
# Revision 1.5  1999/09/23 08:06:56  wiegand
# code cleanup, added installation target
#
# Revision 1.4  1999/09/16 16:31:06  wiegand
# new definition of XXXXclean targets
#
# Revision 1.3  1999/09/15 14:08:03  wiegand
# added doc directory to SUBDIRS
#
# Revision 1.2  1999/09/15 13:20:35  wiegand
# new structure: with subdirectories
#
############################################################

