#! /bin/sh

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/ftp-proxy
NAME=ftp-proxy
DESC=FTP-Proxy
CONF=/etc/proxy-suite/ftp-proxy.conf

test -f $DAEMON || exit 0

# Exit if FTP-Proxy is not configured to run standalone
grep -qi "^[[:space:]]*ServerType[[:space:]]*standalone" $CONF || exit 0

do_start() { start-stop-daemon --start --quiet --exec $DAEMON; }
do_stop() { start-stop-daemon --stop --quiet --oknodo --exec $DAEMON; }

case "$1" in
  start)
	echo -n "Starting $DESC: "
	do_start
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	do_stop || true
	echo "$NAME."
	;;
  reload|force-reload)
        echo "Reloading $DESC configuration files."
        start-stop-daemon --stop --signal 1 --quiet --exec $DAEMON
	;;
  restart)
	echo -n "Restarting $DESC: "
	do_stop || true
	sleep 1
	do_start
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
